<?php
/**
 * Content Page Template
 *
 * The template used for displaying page content in page.php
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}
?>
<div class= container">
<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
	<?php responsive_mobile_entry_top(); ?>
	<div class="feature-image"> 
		<?php get_template_part( 'template-parts/post-meta-page' ); 
	
	// Added filter to get featured_image option working.
	$featured_image = apply_filters( 'responsive_mobile_featured_image', '1' );
	if ( has_post_thumbnail() && $featured_image ) {
		?>
		
		<?php
	} ?>
   <?php responsive_mobile_entry_before(); ?>
<?php echo Su_Shortcodes::button(
	// First argument is array with shortcode attributes
	array(
		'style' => 'flat',
		'background' => '#0099ff',
		'font-size' =>'16px',
		'line-height' =>'56px',
		'border-color' =>'#6cacf4',
		'border-radius' =>'5px',
		'-moz-border-radius' =>'5px',
		'-webkit-border-radius' =>'5px',
		
		 'url'=>"http://www.jcub.edu.au/courses/how-to-apply/international-students.aspx" 
		
	),
	
	/*Second argument is a shortcode content (between opening and closing tags)*/
	'APPLY NOW'
);  ?>
	</div>

	<div class="post-entry container">
		<?php the_content(); ?>
		<?php wp_link_pages( array(
				'before' => '<div class="page-links">' . __( 'Pages:', 'responsive-mobile' ),
				'after'  => '</div>',
		) ); ?>
		<?php get_template_part( 'template-parts/post-data' ); ?>
		<?php responsive_mobile_entry_bottom(); ?>
	</div><!-- .post-entry -->
	<?php responsive_mobile_entry_after(); ?>
</article><!-- #post-## -->
</div>
