<?php
/**
 * Content Single Template
 *
 * The template used for displaying single posts
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.

if ( ! defined( 'WPINC' ) ) {
	die;
}
?>



<?php responsive_mobile_entry_before(); ?>


<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
	<?php responsive_mobile_entry_top(); ?>
	


 <?php if ( 'post' == get_post_type() ) : ?>
            <div class="post-meta">
                <?php
                responsive_mobile_post_meta_data();
                
                // Added filter to get by_line_comments option working.
                $by_line_comments = apply_filters( 'responsive_mobile_by_line_comments', '1' );
                
                if ( ! post_password_required() && ( comments_open() || '0' != get_comments_number() ) && $by_line_comments ) : ?>
                    <span class="comments-link">
                        <span class="mdash">&mdash;</span>
                        <?php comments_popup_link( __( 'No Comments &darr;', 'responsive-mobile' ), __( '1 Comment &darr;', 'responsive-mobile' ), __( '% Comments &darr;', 'responsive-mobile' ) ); ?>
                    </span>
                <?php endif; ?>
            </div><!-- .post-meta -->
        <?php endif; ?>
	<div class="post-entry">
   
		<?php the_content(); ?>
		<?php
			wp_link_pages( array(
				'before' => '<div class="pagination">' . __( 'Pages:', 'responsive-mobile' ),
				'after'  => '</div>',
			) );
		?>
	</div><!-- .post-entry -->
 
	<?php get_template_part( 'template-parts/post-data' ); ?>
	<?php responsive_mobile_entry_bottom(); ?>
</article><!-- #post-## -->
<?php responsive_mobile_entry_after(); ?>
