<?php
/**
 * Template Name: Full Width Pages (no sidebar)
 *
 * Template for pages
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

get_header(); ?>
<div class="container"
   
       <div class = "col-md-3">
    <?php echo Su_Shortcodes::button(
        // First argument is array with shortcode attributes
        array(
            'style' => 'flat',
            'background' => '#2354a3',
            'font-size' =>'16px',
            'line-height' =>'56px',
            'border-color' =>'#6cacf4',
            'border-radius' =>'5px',
            '-moz-border-radius' =>'5px',
            '-webkit-border-radius' =>'5px',
            
             'url'=>"http://localhost/jcub/how-to-apply/" 
            
        ),
        
        /*Second argument is a shortcode content (between opening and closing tags)*/
        'APPLY NOW'
    );  ?>
    
    <div class = "col-md-12">
    <header class="entry-header">
        <?php if( is_single() ) {
            the_title( '<h1 class="entry-title post-title">', '</h1>' );
        } else {
            the_title( sprintf( '<h1 class="entry-title post-title">', esc_url( get_permalink() ) ), '</a></h1>' );
        } ?>
    
       

    </header><!-- .entry-header -->
    
    </div>
</div>

<div class="content container">

	<div id="content" class="content-area">
    
			<main id="main" class="site-main" role="main">

				<?php get_template_part( 'template-parts/loop-header' ); ?>
                

				<?php while ( have_posts() ) : the_post(); ?>

					<?php get_template_part( 'template-parts/content', 'single' ); ?>

					<?php responsive_mobile_post_nav(); ?>

					<?php responsive_mobile_comments_before(); ?>
				
					<?php responsive_mobile_comments_after(); ?>

				<?php endwhile; // end of the loop. ?>
                

			</main><!-- #main -->

			<?php get_sidebar(); ?>
	</div><!-- #content -->
</div>
<?php get_footer(); ?>
